### ISSUE TITLE
Exception raised when trying open Flutter Dev Tools

### ISSUE THREAD

**Issue by elvrusu** [mateusfccp/prototype_constrained_box#1]
Hello, 

I have used this library on a project and when I try to open Flutter Dev Tools > Flutter Inspector I am getting the following exception:
```
======== Exception caught by Flutter framework =====================================================
The following assertion was thrown during a service extension callback for "ext.flutter.inspector.getRootWidgetSummaryTreeWithPreviews":
'package:flutter/src/foundation/diagnostics.dart': Failed assertion: line 2091 pos 15: 'ifTrue != null || ifFalse != null': is not true.

When the exception was thrown, this was the stack: 
#2      new FlagProperty (package:flutter/src/foundation/diagnostics.dart:2091:15)
#3      PrototypeConstrainedBox.debugFillProperties (package:prototype_constrained_box/src/widget.dart:115:20)
#4      Element.debugFillProperties (package:flutter/src/widgets/framework.dart:4958:14)
#5      RenderObjectElement.debugFillProperties (package:flutter/src/widgets/framework.dart:6622:11)
#6      DiagnosticableNode.builder.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:2856:17)
#7      DiagnosticableNode.builder (package:flutter/src/foundation/diagnostics.dart:2859:8)
#8      DiagnosticableNode.emptyBodyDescription (package:flutter/src/foundation/diagnostics.dart:2870:77)
#9      DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1617:13)
...
<asynchronous suspension>
#786    _runExtension.<anonymous closure> (dart:developer-patch/developer.dart:112:11)
<asynchronous suspension>
(elided 2 frames from class _AssertionError)

```

Based on code analysis I was able to determine that the issue is caused by invoking `FlagProperty` without providing `ifTrue` or `ifFalse` parameters. This happens in `package:prototype_constrained_box/src/widget.dart:115:20`.

Thank you!

**Comment by mateusfccp** [comment]
Hello, @elvrusu!

I can reproduce the issue.

The `FlagProperty` class does not make it clear that we should have at least one of them, although it makes sense. I confess that I did not test the widget in Flutter Inspector, tho 😅

**Comment by mateusfccp** [comment]
2.0.2 has been released with the fix
